server:
  port: 8766

spring:
  application:
    name: springcloud-goods-reg
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dubbo?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 500
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml